### ISSUE TITLE
More parity with other languages

### ISSUE THREAD

**Issue by sandstrom** [wasmerio/wasmer-ruby#47]
It seems like the ruby sdk/client is still a bit behind the other languages. Would be awesome if more functionality was supported, for example terminate in host call, serialization and exposing host (imported) functions.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/122287/116046866-c61a6300-a673-11eb-87a2-125994daad62.png">

Source:
https://docs.wasmer.io/ecosystem/wasmer/wasmer-features#language-embeddings

For our use case, we'd like to pass in a bunch of data from the host (e.g. JSON like data), pass in a bunch of functions, accessible to the WASM-code, and then call the function exposed by WASM (with ability to abort/terminate from host).

**Comment by Hywan** [comment]
Yup, it's in my agenda to rewrite this extension as it's been done for Python, Go and PHP!

**Comment by sandstrom** [comment]
@Hywan Awesome! 😄

**Comment by Hywan** [comment]
The project has been fully rewritten in #48. I'm updating the documentation right now, but if you check #48 you will see the project is now on-par with [`wasmer-python`](https://github.com/wasmerio/wasmer-python), [`wasmer-go`](https://github.com/wasmerio/wasmer-go), [`wasmer-php`](https://github.com/wasmerio/wasmer-php) and [`wasmer`](https://github.com/wasmerio/wasmer) itself.

**Comment by sandstrom** [comment]
Awesome @Hywan !! 🎉
